### ISSUE TITLE
Rust: generate trait that covers access-to-the-name-of-an-enum such that one can write generic code against all enums.

### ISSUE THREAD

**Issue by graydon** [stellar/xdrgen#108]
Ideally same for unions and any other types that have common `impl` blocks. Abstracting over all-types-with-the-same-impl-block is what traits are for!

**Comment by leighmcculloch** [comment]
The name() fn could also be const (#106), so we should have both, an inherent const name() fn, and then the trait impl that calls the inherent const name(). We can't have const fns inside a trait, so both the inherent and trait impls are useful.
