### ISSUE TITLE
JS: Using `set` as an arm name for SCSpecTypeDef breaks the js-xdr package.

### ISSUE THREAD

**Issue by wildework** [stellar/xdrgen#153]
### What version are you using?

The latest commit on `next`, `df18148747e807618acf4639db41c4fd6f0be9fc`.

### What did you do?

I generate the JavaScript version of XDR using `xdrgen` which imports `js-xdr`. Because `js-xdr` uses the keyword `set` when it tries to interact with `SCSpecTypeDef` it breaks.

```
union.js:65 Uncaught (in promise) Error: set not set
    at ChildUnion2.get (union.js:65:15)
    at ChildUnion2.get [as set] (union.js:219:23)
    at ChildUnion2.Union2 (union.js:44:10)
    at new ChildUnion2 (union.js:146:111)
    at Function.read (union.js:120:14)
    at var-array.js:60:33
    at baseTimes (_baseTimes.js:15:21)
    at times (times.js:44:16)
    at VarArray2.read (var-array.js:59:26)
    at struct.js:57:26
```

The offending XDR is here.

```
union SCSpecTypeDef switch (SCSpecType type)
{
case SC_SPEC_TYPE_VAL:
case SC_SPEC_TYPE_U64:
case SC_SPEC_TYPE_I64:
case SC_SPEC_TYPE_U128:
case SC_SPEC_TYPE_I128:
case SC_SPEC_TYPE_U32:
case SC_SPEC_TYPE_I32:
case SC_SPEC_TYPE_BOOL:
case SC_SPEC_TYPE_SYMBOL:
case SC_SPEC_TYPE_BITSET:
case SC_SPEC_TYPE_STATUS:
case SC_SPEC_TYPE_BYTES:
case SC_SPEC_TYPE_ADDRESS:
    void;
case SC_SPEC_TYPE_OPTION:
    SCSpecTypeOption option;
case SC_SPEC_TYPE_RESULT:
    SCSpecTypeResult result;
case SC_SPEC_TYPE_VEC:
    SCSpecTypeVec vec;
case SC_SPEC_TYPE_MAP:
    SCSpecTypeMap map;
case SC_SPEC_TYPE_SET:
    SCSpecTypeSet set;
case SC_SPEC_TYPE_TUPLE:
    SCSpecTypeTuple tuple;
case SC_SPEC_TYPE_BYTES_N:
    SCSpecTypeBytesN bytesN;
case SC_SPEC_TYPE_UDT:
    SCSpecTypeUDT udt;
};
```

Specifically this line.

```
// ...
case SC_SPEC_TYPE_SET:
    SCSpecTypeSet set;
// ...
```

### What did you expect to see?

No errors when using `js-xdr` with the latest XDR.

### What did you see instead?

The `set not set` error.

We can fix this by simply uppercasing the `set` to `Set`, or picking another name.

**Comment by leighmcculloch** [comment]
Moving this issue to the xdrgen repo because this is an issue with xdrgen generating broken code.

**Comment by ire-and-curses** [comment]
@wildework Can you expand on why you think this error occurs? `set` isn't a reserved word in JS, is it?

**Comment by wildework** [comment]
@ire-and-curses I believe it's because here https://github.com/stellar/js-xdr/blob/master/src/union.js#L136 when `aSwitch.name` is `set` it dynamically replaces the method `set` defined here https://github.com/stellar/js-xdr/blob/master/src/union.js#L13 . Once the `set` method is gone, the union instance stops working.

JavaScript is very liberal with runtime class redefinitions and so it allows switching out a class defined method.
