### ISSUE TITLE
Publish as gem

### ISSUE THREAD

**Issue by raymens** [stellar/xdrgen#18]
I cannot find the gem as mentioned in the readme. Is it published?

**Comment by nullstyle** [comment]
We haven't published it yet, no.  For now, I recommend just using a Gemfile to make it available, for example:  https://github.com/stellar/ruby-stellar-base/blob/master/Gemfile

**Comment by ire-and-curses** [comment]
For the record: discussed this yesterday - yes we should do it soon.

**Comment by abuiles** [comment]
This has been published as a gem, you can do now `gem install xdrgen`
