### ISSUE TITLE
Merge in downstream C# generator

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/xdrgen#58]
There is a C# generator located here:
https://github.com/fracek/xdrgen/tree/csharp

The generator is currently being used by the [dotnet-stellar-sdk](https://github.com/elucidsoft/dotnet-stellar-sdk) and is discussed on that projects README [here](https://github.com/elucidsoft/dotnet-stellar-sdk#xdr-generation).

If the repo owner of that fork, @fracek, is willing, I think we should import that logic into xdrgen. We can add tests, but also we could mark it as experimental in the README for a period of time if it is at all incomplete.

@fracek Would you be up for bringing your csharp implementation upstream?

@bartekn Any known reason this has happened yet, or any prior context I might be missing?

_Note: There is a 4 year old PR (#20) in this repo adding C# support, however it looks like it includes code that is licensed as LGPL and @nullstyle pointed out [here](https://github.com/stellar/xdrgen/pull/20#issuecomment-173017143) that there may be issues accepting that contribution due to that. I doubt we could accept that contribution because of that._

cc @accordeiro @bartekn

**Comment by fracek** [comment]
I imported the code for use in `dotnet-stellar-sdk`, but I'm not the original author, I only made some changes to it to. I think @michaeljmonte is the copyright owner of the code.

**Comment by leighmcculloch** [comment]
@fracek It looks like the code in your [csharp](https://github.com/fracek/xdrgen/tree/csharp) branch is a copy from https://github.com/michaeljmonte/xdrgen/commit/f1fa4170e511c62776119970132ecd8b551f0c1c plus your own ulong fix. Is that correct?

The https://github.com/michaeljmonte/xdrgen repo looks like it contains other changes in addition to the changes you're using, but those additional changes contain references to LGPL so I don't think all those changes could be imported here, an Apache 2.0 licensed code base.

@michaeljmonte would you be willing to contribute your non-LGPL commit (https://github.com/michaeljmonte/xdrgen/commit/f1fa4170e511c62776119970132ecd8b551f0c1c) upstream to this repo in a PR?

**Comment by michaeljmonte** [comment]
Sure, it has been awhile since I worked on it, but I can take a look later on tonight, or tomorrow sometime.

**Comment by michaeljmonte** [comment]
Added PR from my fork to the stellar/xdrgen master. See #59

**Comment by leighmcculloch** [comment]
#59 has been merged 🎉. Thanks all!

**Comment by leighmcculloch** [comment]
@fracek I'm not sure if you need this but I noticed your branch had a change on it: https://github.com/fracek/xdrgen/commit/024de675b97e887ff1a1e19d3d446d1c7ba640f9. If that is required, could you open a PR on this repo adding it to close out support for the dotnet-stellar-sdk xdr code gen?

**Comment by fracek** [comment]
@leighmcculloch Yep, I just noticed that if I run this generator the `Encode` and `Decode` methods in `UInt32.cs` look wrong. I'll prepare a PR for this.
