### ISSUE TITLE
Merge in downstream Rust generator

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/xdrgen#76]
Now that more folks are writing Rust code that interacts with Stellar, including us with [rs-stellar-contract-sdk](https://github.com/stellar/rs-stellar-contract-sdk), there would be a benefit to maintaining a Rust generator inside xdrgen.

There is a Rust generator implemented in a fork of xdrgen: [aurora-rs/xdrgen](https://github.com/aurora-rs/xdrgen).
The generator is currently being used by the [aurora-rs/stellar-base-rs](https://github.com/aurora-rs/stellar-base-rs) repo.
The generator generates types from .x definitions, and relies on the `xdr-rs-serialize` crate for the serialization.

It looks like @fracek is the author of the commits at that fork that add Rust support. @fracek also authored the C# generator that was added into xdrgen in #58 / #59.

cc @graydon

**Comment by leighmcculloch** [comment]
Cursory review:

Somethings that are missing from the generator that are noticeable in the test xdr files are:
- Constants in typedefs – They don't seem to maintain the fixed/var attributes, so they all become var-length I think. Attrs are maintained on typedefs without consts, and on fields.
- Simple types – There's a todo comment about a missing attribute on simple type field definitions. Not sure of impact of this yet, will have to dig in. Might be related to the above.

Some other things I note that might be worth changing:
- Fixed length arrays all materialize as Vec's, which are naturally variable length. In other generators, like the Go generator, we map these to natively fixed length arrays.

**Comment by leighmcculloch** [comment]
@fracek You appear to be the author of https://github.com/aurora-rs/xdrgen/commit/20ae1636da29bfc30dbe3604ee9c25856b21a3ac. Is there anything I should know about the functionality in that rust generator before bringing it upstream?

**Comment by fracek** [comment]
Like you said there are some missing pieces because I was trying to get something out quickly. The code generated requires some manual adjustments before it works. Since you're more familiar with xdrgen you can probably implement what's missing and get a working full generator.
